### ISSUE TITLE
Some resources missing - Subnets, S3 and others

### ISSUE THREAD

**Issue by restanislao** [awslabs/workload-discovery-on-aws#265]
When I expand a VPC not all subnets are showing.  They are not found in when searching resources either.  

Reviewed gremlin function logs per trouble shooting document, Searching for error "400":

2022-03-07T04:32:45.381Z	f87f65da-d5e1-4458-ab9b-c723ffb1fdcc	INFO	ResponseError: Server error: {
    "code": "ConstraintViolationException",
    "requestId": "3fc57ae2-cd53-4650-a944-8e801397eeef",
    "detailedMessage": "Vertex with id already exists: "
} (499)
    at Connection._handleMessage (/var/task/node_modules/gremlin/lib/driver/connection.js:282:9)
    at WebSocket.<anonymous> (/var/task/node_modules/gremlin/lib/driver/connection.js:130:43)
    at WebSocket.emit (events.js:400:28)
    at WebSocket.emit (domain.js:475:12)
    at Receiver.receiverOnMessage (/var/task/node_modules/ws/lib/websocket.js:789:20)
    at Receiver.emit (events.js:400:28)
    at Receiver.emit (domain.js:475:12)
    at Receiver.dataMessage (/var/task/node_modules/ws/lib/receiver.js:413:14)
    at /var/task/node_modules/ws/lib/receiver.js:379:23
    at /var/task/node_modules/ws/lib/permessage-deflate.js:298:9 {
  statusCode: 499,
  statusMessage: '{"code":"ConstraintViolationException","requestId":"3fc57ae2-cd53-4650-a944-8e801397eeef","detailedMessage":"Vertex with id already exists: "}',
  statusAttributes: {}
}

**Comment by svozza** [comment]
I suspect this issue is related to scaling limitation in v1.x.x. The old discovery process made an API call to AWS Config for every resource it found. For regions with ~2500 resources, this meant Config would start applying rate limiting to these calls and eventually the whole discovery process would hang and not complete. We have addressed this issue in version v2.0.0 and now make far fewer calls to Config when discovering resources. This new version was [released](https://aws.amazon.com/solutions/implementations/workload-discovery-on-aws/) today, and the 2500 resource limit no longer applies.

**Comment by svozza** [comment]
Closing due to inactivity. Please feel free to reopen.
